import pyautogui
import setuptools
import os
from time import sleep

#importionsDone

def chrome():
    windows = pyautogui.locateCenterOnScreen('images/windows.png')
    pyautogui.click(windows)
    windows1 = pyautogui.locateCenterOnScreen('images/windows1.png')
    pyautogui.click(windows1)
    pyautogui.write('chrome')
    sleep(0.69)
    chrome = pyautogui.locateOnScreen('images/chrome.png')
    pyautogui.click(chrome)
    sleep(0.69)
    
def newTab():
    cords = pyautogui.locateCenterOnScreen('images/newTab.png')
    pyautogui.click(cords)

def startTypingTest():
    stt = pyautogui.locateCenterOnScreen('images/stt.png')
    pyautogui.click(stt)

#preDefsDone

chrome()
sleep(0.69)
newTab()
pyautogui.write('https://typingtest.com/')
pyautogui.press('enter')
sleep(5)
startTypingTest()

def aesopFile():
    pyautogui.typewrite('Aesop was one of the great Greek writers. He is best known for his fables, stories that have a moral. They teach us something about how we should live our lives. Aesop wrote thousands of these stories. Here are a few.') 
    sleep(3)
    pyautogui.typewrite('The Wolf in Sheeps Clothing')
    sleep(3)
    pyautogui.typewrite('Once upon a time, a Wolf decided to disguise the way he looked. He thought it would help him get food more easily. He put on the skin of a sheep, then he went out with the flock into the pasture. Even the shepherd was fooled by his clever costume. In the evening, the shepherd put him in with the rest of the sheep.')
    sleep(3)
    pyautogui.typewrite('He closed the gate and made sure it was secure before he went to bed. In the middle of the night, he came back to the fold to get some meat for the next day. Instead of a sheep, though, he grabbed the Wolf, killing him instantly.')
    sleep(3)
    pyautogui.typewrite('Those who look to harm others will be harmed themselves.')
    sleep(3)
    pyautogui.typewrite('The Bat and the Weasel')
    sleep(3)
    pyautogui.typewrite('A Bat fell on the ground and was caught by a Weasel. It begged the Weasel to spare its life, but the Weasel refused. It told the Bat that birds, by nature, were its enemy. The Bat assured him that it was not a bird, it was a mouse. The Weasel thought a moment, then set it free. A while later, the Bat fell again to the ground, and it was caught by another Weasel.')
    sleep(3)
    pyautogui.typewrite(' It begged this Weasel not to eat him, either. The Weasel, though, said it did not like mice at all and would eat it. The Bat told the Weasel that it was not a mouse, but a bat. The second Weasel had no good answer, so he let it go.')
    sleep(3)
    pyautogui.typewrite('The Bat knew it is always wise to turn events to your advantage. ')
    sleep(3)
    pyautogui.typewrite('The Lion and the Mouse') 
    sleep(3)
    pyautogui.typewrite('A sleeping Lion was woken up by a Mouse running over his face. He got up angrily and caught the scared little Mouse. He was about to kill the Mouse, but it said in its squeaky little voice, "If you would only spare my life, I would be sure to repay your kindness." The Lion laughed at such nonsense, but he let him go. A short time later, though, the Lion was caught by some hunters.')
    sleep(3)
    pyautogui.typewrite(' They bound him by ropes to the ground. The Mouse recognized his roar, and he rushed over and gnawed the rope with his teeth, setting the Lion free. The Mouse said "You laughed at the idea of my ever being able to help you. Now you know that it is possible for even a small little Mouse to help a great big Lion."   ')
    sleep(5)

def aesop():
    sleep(5)
    if (pyautogui.locateOnScreen('images/aesop.png') is not None):
        aesopFile()
        aesopFile()

def tigerFile():
    pyautogui.typewrite('The tiger, Panthera tigris, one of the worlds most magnificent and revered animals, faces possible extinction in the wild. Since the turn of the century, its habitat and numbers have been reduced by 95 percent. For a million years the "King of the Jungle" lorded over a territory stretching from eastern Turkey to the Russian Far East, its forest home extending northward to Siberia and southward into Bali.')
    sleep(3)
    pyautogui.typewrite(' In this century alone, the Bali, Javan, and Caspian tigers have become extinct. Tragically, the remaining five sub-species are at risk of meeting the same fate. The tiger faces an onslaught of poaching throughout its range. In the 1990s, hundreds of tigers have been killed to meet the demand for their bones and other parts, which are used for traditional medicines in China, Taiwan, and Korea, and exported to Chinese communities all over the world, including those in Australia, Europe, and the USA.')
    sleep(3)
    pyautogui.typewrite('Following a tip-off from TRAFFIC India, WWFs local wildlife monitoring network, New Delhi police in 1993 seized a half tonne (500 kg) of tiger bones, representing the remains of between 40 and 50 tigers. In October 1995, the Indian government told the CITES (Convention on International Trade in Endangered Species of Wild Fauna and Flora) ')
    sleep(3)
    pyautogui.typewrite('Asia Regional Meeting in Tokyo that it had seized another half tonne of tiger bone so far that year. During the same gathering, Indonesia stated that poaching of the Sumatran tiger was "uncontrolled" and said illegal hunting and trading pressures on rhinos and tigers were "overwhelming".')
    sleep(3)
    pyautogui.typewrite('Earlier in 1995, Cambodia reported that every month 12 to 15 of its tigers were being killed, and in Vietnam five known deaths were confirmed during the first six months of 1995. Experience has shown that this is only the tip of the iceberg because the trade is clandestine.')
    sleep(3)
    pyautogui.typewrite(' Poverty is killing the tiger in Vietnam, say some scientists. In 1998, farmers throughout Southeast Asia, particularly those engaged in subsistence agriculture, suffered from one of the worst droughts in history - so they have turned to the sale of wildlife as a means of income. The tiger in Indochina is possibly disappearing faster than anywhere else in the world.')
    sleep(3)
    pyautogui.typewrite(' Conservation work has been notoriously difficult as economic hardship and war have hampered protection, research, and training. Some of the forests that do remain are hauntingly silent. ')
    sleep(5)

def tiger():
    sleep(5)
    if (pyautogui.locateOnScreen('images/tiger.png') is not None):
        tigerFile()
        tigerFile()
        tigerFile()
        tigerFile()

def zebraFile():
    pyautogui.typewrite('Zebras - Africas striped horses')
    sleep(3)
    pyautogui.typewrite('There are three species of zebra, all found in Africa. These close relatives of the domestic horse  can be recognized easily by their black and white striped body.')
    pyautogui.typewrite('The Plains or Burchells zebra is found in open or wooded grasslands from northern South Africa westwards to Etosha Pan in Namibia and north as far as southern Somalia and southern Sudan. The Mountain zebra is found in semi-desert or savanna grasslands in Namibia and South Africa. Grevys zebra is found in hot, dry semi-deserts in southern and eastern Ethiopia and northern Kenya.')
    sleep(3)
    pyautogui.typewrite('Plains and Mountain zebras stand about 1.3 m at the shoulder and weigh 200 - 380 kg. Grevys zebras are a little bigger - about 1.4-1.6 m high and up to 450 kg. All zebras have a neat, upright mane.')
    sleep(3)
    pyautogui.typewrite('The three species of zebra can be identified by their stripes. The Plains zebra has stripes that reach under the belly. They broaden at the flanks and bend backwards towards the rump, forming a Y-shaped saddle')
    sleep(3)
    pyautogui.typewrite('The stripes on Mountain zebras stop short of the white belly and form a distinctive pattern on the rump. Mountain zebras also have a small flap or dewlap on their throats.')
    sleep(3)
    pyautogui.typewrite('Grevys zebra has a white, unstriped belly, narrow stripes, and large rounded ears with white tips.')
    sleep(3)
    pyautogui.typewrite('Zebras are generally grazers, feeding mainly on grass. They prefer tall grasses which most other species seem to avoid. Grevys zebras also eat leaves. Zebras often mingle with other herbivores in mixed herds. This is partly for mutual defence: the larger the herd, the less likely any individual animal will be picked off by a lion. An alarm call by a zebra alerts the whole herd to danger.')
    sleep(3)
    pyautogui.typewrite(' Also, because zebras remove long, coarse grasses, they help other grazing animals such as wildebeeste or buffalo to find shorter, more succulent grazing.')
    sleep(5)

def zebra():
    if (pyautogui.locateOnScreen('images/zebra.png') is not None):
        zebraFile()
        zebraFile()
        zebraFile()
        zebraFile()

def ozFile():
    pyautogui.typewrite('Dorothy lived in the midst of the great Kansas prairies, with Uncle Henry, who was a farmer, and Aunt Em, who was the farmers wife.  Their house was small, for the lumber to build it had to be carried by wagon many miles.  There were four walls, a floor and a roof, which made one room; and this room contained a rusty looking cookstove, a cupboard for the dishes')
    sleep(3)
    pyautogui.typewrite(', a table, three or four chairs, and the beds.  Uncle Henry and Aunt Em had a big bed in one corner, and Dorothy a little bed in another corner.  There was no garret at all,')
    sleep(3)
    pyautogui.typewrite(' and no cellar--except a small hole dug in the ground, called a cyclone cellar, where the family could go in case one of those great whirlwinds arose, mighty enough to crush any building in its path.  It was reached by a trap door in the middle of the floor, from which a ladder led down into the small, dark hole.')
    sleep(3)
    pyautogui.typewrite('When Dorothy stood in the doorway and looked around, she could see nothing but the great gray prairie on every side.  Not a tree nor a house broke the broad sweep of flat country that reached to the edge of the sky in all directions.  The sun had baked the plowed land into a gray mass, with little cracks running through it')
    sleep(3)
    pyautogui.typewrite('. Even the grass was not green, for the sun had burned the tops of the long blades until they were the same gray color to be seen everywhere.  Once the house had been painted, but the sun blistered the paint and the rains washed it away, and now the house was as dull and gray as everything else.')
    sleep(3)
    pyautogui.typewrite('When Aunt Em came there to live she was a young, pretty wife. The sun and wind had changed her, too.  They had taken the sparkle from her eyes and left them a sober gray; they had taken the red from her cheeks and lips, and they were gray also.  She was thin and gaunt, and never smiled now.  When Dorothy, who was an orphan,')
    sleep(3)
    pyautogui.typewrite(' first came to her, Aunt Em had been so startled by the childs laughter that she would scream and press her hand upon her heart whenever Dorothys merry voice reached her ears; and she still looked at the little girl with wonder that she could find anything to laugh at.')
    sleep(3)
    pyautogui.typewrite('Uncle Henry never laughed.  He worked hard from morning till night and did not know what joy was.  He was gray also, from his long beard to his rough boots, and he looked stern and solemn, and rarely spoke.')
    sleep(3)
    pyautogui.typewrite('It was Toto that made Dorothy laugh, and saved her from growing as gray as her other surroundings.  Toto was not gray; he was a little black dog, with long silky hair and small black eyes that twinkled merrily on either side of his funny,')
    sleep(3)
    pyautogui.typewrite(' wee nose.  Toto played all day long, and Dorothy played with him, and loved him dearly.')
    sleep(3)
    pyautogui.typewrite('Today, however, they were not playing.  Uncle Henry sat upon the doorstep and looked anxiously at the sky, which was even grayer than usual.  Dorothy stood in the door with Toto in her arms, and looked at the sky too.  Aunt Em was washing the dishes.')
    sleep(5)

def oz():
    if (pyautogui.locateOnScreen('images/oz.png') is not None):
        ozFile()
        ozFile()
        ozFile()

def enchantedFile():
    pyautogui.typewrite('It is a strange fact, for which I do not expect ever satisfactorily to account, and which will receive little credence even among those who know that I am not given to romancing--it is a strange fact, I say, that the substance of the following pages has evolved itself during a period of six months, more or less, between the hours of midnight and four oclock in the morning')
    sleep(3)
    pyautogui.typewrite(', proceeding directly from a type-writing machine standing in the corner of my library, manipulated by unseen hands. The machine is not of recent make. It is, in fact a relic of the early seventies, which I discovered one morning when, suffering from a slight attack of the grip, I had remained at home and devoted my time to pottering about in the attic,')
    sleep(3)
    pyautogui.typewrite(' unearthing old books, bringing to the light long-forgotten correspondences, my boyhood collections of "stuff," and other memory-inducing things. Whence the machine came originally I do not recall. My impression is that it belonged to a stenographer once in the employ of my father, who used frequently to come to our house to take down dictations. However this may be, the machine had lain hidden by dust and the flotsam and jetsam of the house for twenty years')
    sleep(3)
    pyautogui.typewrite(', when, as I have said, I came upon it unexpectedly. Old man as I am--I shall soon be thirty--the fascination of a machine has lost none of its potency. I am as pleased to-day watching the wheels of my watch "go round" as ever I was, and to "monkey" with a type-writing apparatus has always brought great joy into my heart-- though for composing give me the pen. Perhaps I should apologize for the use here of the verb monkey,')
    sleep(3)
    pyautogui.typewrite(' which savors of what a friend of mine calls the "English slanguage," to differentiate it from what he also calls the "Andrew Language." But I shall not do so, because, to whatever branch of our tongue the word may belong, it is exactly descriptive, and descriptive as no other word can be, of what a boy does with things that click and "go," and is therefore not at all out of place in a tale which I trust will be regarded as a polite one.')
    sleep(3)
    pyautogui.typewrite('The discovery of the machine put an end to my attic potterings. I cared little for finding old bill-files and collections of Atlantic cable-ends when, with a whole morning, a type-writing machine, and a screw-driver before me I could penetrate the mysteries of that useful mechanism. I shall not endeavor to describe the delightful sensations of that hour of screwing and unscrewing; they surpass the powers of my pen.')
    sleep(3)
    pyautogui.typewrite(' Suffice it to say that I took the whole apparatus apart, cleaned it well, oiled every joint, and then put it together again. I do not suppose a seven-year-old boy could have derived more satisfaction from taking a piano to pieces. It was exhilarating, and I resolved that as a reward for the pleasure it had given me the machine should have a brand-new ribbon and as much ink as it could consume. And that, in brief, is how it came to be that this machine of antiquated pattern was added to the library bric-a-brac. To say the truth, it was of no more practical use than Baryes dancing bear, a plaster cast of which adorns my mantel-shelf, so that when I classify it with the bric-a-brac I do so advisedly. I frequently tried to write a jest or two upon it, but the results were extraordinarily like Sir Arthur Sullivans')
    sleep(3)
    pyautogui.typewrite(' experience with the organ into whose depths the lost chord sank, never to return. I dashed off the jests well enough, but somewhere between the keys and the types they were lost, and the results, when I came to scan the paper, were depressing. And once I tried a sonnet on the keys. Exactly how to classify the jumble that came out of it I do not know, but it was curious enough to have appealed strongly to DIsraeli or any other')
    sleep(3)
    pyautogui.typewrite(' collector of the literary oddity. More singular than the sonnet, though, was the fact that when I tried to write my name upon this strange machine, instead of finding it in all its glorious length written upon the paper, I did find "William Shakespeare" printed there in its stead. Of course you will say that in putting the machine together I mixed up the keys and the letters. I have no doubt that I did, but when I tell you that there have been times when, looking at myself in the glass, I have fancied that I saw in my mirrored face the lineaments of the great bard; that the contour of my head is precisely the same as was his;')
    sleep(3)
    pyautogui.typewrite(' that when visiting Stratford for the first time every foot of it was pregnant with clearly defined recollections to me, you will perhaps more easily picture to yourself my sensations at the moment.')
    sleep(5)

def enchanted():
    if (pyautogui.locateOnScreen('images/enchanted.png') is not None):
        enchantedFile()
        enchantedFile()
        enchantedFile()
        enchantedFile()

def astronautsFile():
    pyautogui.typewrite('The word "astronaut" derives from the Greek words meaning "star" and "sailor." These men and women -- Alan Shephard, John Glenn, Jr., Sally Ride, to name a few -- conjure up images of bravery and adventure. They are modern heroes, helping humanity reach for the stars.')
    sleep(3)
    pyautogui.typewrite('When the space program began in 1959, there were only seven such people in the entire country. They all were then -- or had been in the past -- in the armed forces. Most of them were test pilots, used to the dangers that came from "pushing the envelope." That was only 36 years ago, and since then much has changed.')
    sleep(3)
    pyautogui.typewrite('Today the Americans who make up the shuttle crews are comprised of every race, creed, color, and gender. As of May 2, 1993, 180 men and 21 women astronauts were Caucasian, six men and one woman were African-American, three men and one woman were Hispanic, and two men were of Asian descent.')
    sleep(3)
    pyautogui.typewrite('NASA, the National Aeronautics and Space Administration, chooses its astronauts from an increasingly diverse pool of applicants that "looks like America." Thousands of applications come in from all over the world; from these, approximately 100 men and women are chosen for an intensive astronaut candidate training program every two years. "I cannot imagine a better career. Ive done more than I could ever have imagined. Im thankful that Ive been at the right place at the right time," says astronaut Kenneth S. Reightler.')
    sleep(3)
    pyautogui.typewrite('The training is demanding, but the study time involved is no longer than that of any other professional career requiring graduate/post-graduate study. If becoming an astronaut is a dream, held long and steadfast, then this labor will be one of love.')
    sleep(3)
    pyautogui.typewrite(' "Start with the basics and get them down first ... you cant do anything without math and science." At this level, students should read everything they can get their hands on about astronauts and space in general. Later, once they have found a specific field of interest, they can begin to focus on that.')
    sleep(3)
    pyautogui.typewrite('The preparation for becoming an astronaut actually begins in elementary school. "It is here that the foundations are laid down and then built upon," comments Colonel Charlie Bolden, Deputy Commandant of Midshipmen at the U.S. Naval Academy.')
    sleep(3)
    pyautogui.typewrite('But theres more than book learning involved. Other skills Bolden feels are integral to becoming an astronaut are: being able to work as a team player; understanding and appreciating your ethnic, cultural, and American history; and maintaining a grasp on current events.')
    sleep(3)
    pyautogui.typewrite('Bolden does not hold the opinion that Americas young people are less equipped than their foreign counterparts. "I listen to people say that American students cant do this and cant do that. I dont buy into or accept that at all. Kids are just as sharp as when I came up. Its just motivation that may be lacking," Bolden said.')
    sleep(3)
    pyautogui.typewrite('It is also interesting to note that out of 195 former and present astronauts, 123 (64%) have taken part in some form of scouting. Scouting develops a sense of discipline, as well as particular skills. Both are crucial to becoming part of the astronaut team.')
    sleep(3)
    pyautogui.typewrite('Once students reach high school, it is particularly important that they earn the best possible grades as well as high standardized test scores (SAT and/or ACT). NASA looks for the best and the brightest, so it makes sense that they would look at how well students apply themselves to their studies. At this point, too, students should begin to think about a specific direction of study, such as engineering, biological or physical science, or mathematics. This will help them direct their education once they get to college.')
    sleep(3)
    pyautogui.typewrite('Again, though, books are only part of the process. Its a good idea to look for out-of-school opportunities like internships or apprenticeships, summer programs, and fieldwork, to help balance textbook learning. After all, going into space is a real-world -- not a virtual -- experience; the more experience you bring to it, the better youll be able to deal with the demands of the job. Internships are also a good way of finding out if your career choice is the right one for you. Many students, when faced with the realities of a particular field, decide its not what they wanted, after all. Its better to decide early on that this is the case, before you devote a lot of time and effort to something you dont enjoy.')
    sleep(3)
    pyautogui.typewrite('But choose your activities wisely. "If you do things thinking that, This will look good on a resume, or Im not going to like it but itll help me get selected someday, you will do yourself a disservice. Youre not going to do as well as you would at something in which youre interested," said Reightler.')
    sleep(3)
    pyautogui.typewrite('The "minimum degree requirement" for an astronaut is a Bachelors degree from an accredited institution. Three years of related increasingly responsible professional experience must follow that degree. Most astronauts to date, however, have continued with their education to the post-graduate (Masters and Ph.D.) levels; they have been able to substitute that education for all or part of their work experience requirement.')
    sleep(3)
    pyautogui.typewrite('NASA contributes funds to 51 colleges and universities through its Space Grant Consortia. If you attend one of these institutions, you are ensured that the curriculum for space programs will conform with the guidelines NASA finds acceptable. However, you can attend any college or university that you wish, since almost all offer degrees in technical fields, math, and science. You should check with a guidance/college counselor -- and NASA -- before you go to confirm that the school will offer the subjects you need.')
    sleep(3)
    pyautogui.typewrite('Regardless of which school you do attend, you once again need to go for the grades. For one thing, you will need them to be accepted into a good Masters program. And for another, NASA needs applicants who can demonstrate success at the higher-education levels.')
    sleep(3)
    pyautogui.typewrite('Math and science are obviously critical to becoming an astronaut, but they are not the only subjects you will need to get where youre going. English -- an ability to communicate, both written and verbally -- is also vital. So is history, not just of the space program, but of the world. And Bolden, who had to wake up extra early to attend a class in basic Russian language to prepare for his mission with a cosmonaut, suggests that every American should be -- at the very least -- bilingual.')
    sleep(3)
    pyautogui.typewrite('"Space," he says, "is a multinational and multicultural operation. Working with Russian cosmonauts is very difficult if astronauts dont know anything about Russian culture and their history as a people." This is also increasingly true as construction of the International Space Station gets underway.')
    sleep(3)
    pyautogui.typewrite('But, says Dr. Ellen Ochoa, a Mission Specialist and the first Hispanic woman in space, "there isnt one particular type of work experience that NASA is looking for. NASA -- like any other employer -- wants to know how well a person has done. If you come from a research background, theyd look at published work in technical journals, lecturing or TA experience, and also any awards that you may have won. Everyone should have summer jobs. You need some sort of experience."')
    sleep(3)
    pyautogui.typewrite('College-level experience will also help you to understand what particular companies are looking for in terms of hiring policies and experience levels. And many students are offered jobs, either when their internship is completed or upon graduation.')
    sleep(3)
    pyautogui.typewrite('So now that youve got the degree and some experience, how do you qualify to become an astronaut? The first step is to fill out an application -- specifically, U.S. Government Form 171, which you send to the Johnson Space Center (JSC) in Houston, Texas. There it will be reviewed and ranked according to height considerations (you must be at least 58.5 inches), experience, and expertise (i.e. geologists, physicists, chemists, biologists etc.). The competition is fierce -- about 4,000 individuals apply every two years, and the slots are limited.')
    sleep(3)
    pyautogui.typewrite('And if the applicant is looking for a pilot/commander position in the program, then he/she must also be prepared to log in at least 1,000 hours of flight time in command of a jet aircraft prior to consideration. Most of the current and former pilot/commander positions have been filled historically by men who have served or are currently active in the United States Armed Forces. There are only a few exceptions. During training all crew members will train aboard a T-38 jet. The controls are identical to that of the Space Shuttle and, therefore, the jet can be used as a flight simulator either on the ground or in actual flight.')
    sleep(3)
    pyautogui.typewrite('Once the initial ranking is complete, the applications go through a second, more stringent, round to narrow down the field. From the initial 4,000 applicants, only about 118 are asked to come to the JSC and undergo a week of interviews, medical examinations, and basic orientation.')
    sleep(3)
    pyautogui.typewrite('Ochoa noted that the Astronaut Selection Board (ASB) generally looks for people who have done very well in a technical field. And very well does not mean just their grades -- candidates should make sure they have sterling recommendations, especially from undergraduate and graduate school professors who can attest to their problem solving abilities, communication skills, and their ability to work well as part of a team.')
    sleep(3)
    pyautogui.typewrite('The ASB interviews each person and assigns him or her a rating based on: experience and potential, motivation, ability to function as a member of a team, communication skills, and adaptability. Applicants who have impeccable school records and plenty of outside experience but who do not possess the required interpersonal skills for the position, may be rejected solely on that basis. Being an astronaut really means being part of a team.')
    sleep(3)
    pyautogui.typewrite('A significant number of applicants do not meet medical standards, and still others withdraw after gaining a complete understanding of the very demanding job. Based on the information collected during this investigation, ASB will choose its final candidates and pass that recommendation on to the NASA Administrator; he or she will make the final choices. Once selected, candidates begin a rigorous training program.')
    sleep(3)
    pyautogui.typewrite('As with any other career, being an astronaut has drawbacks. One commonly shared among astronauts is the intense workload and the lack of time for their families. "With this job you could work 24 hours a day, seven days a week, and still not get everything done. You have to strike a balance--that is the key," says Reightler. "There can be long hours that are unpredictable. Travel is involved especially during the busiest times -- three months before and two months after a launch," agreed Ochoa.')
    sleep(3)
    pyautogui.typewrite('And if an applicant has hopes for a large salary -- say, comparable to those in the private sector -- they should look elsewhere. Astronauts begin their salary in accordance with the U.S. Government pay scale at GS-11 status (approximately $39,000) and top off at GS-14 status (approximately $78,000). Thats not a whole lot for a dangerous job. But for those who dream of going into space, the pay is one of the lesser considerations.')
    sleep(5)

def astronauts():
    if (pyautogui.locateOnScreen('images/astronauts.png') is not None):
        astronautsFile()

def baseballFile():
    pyautogui.typewrite('Baseball has been the national pastime in the United States since the middle of the 1800s. Each period has had a unique flavor, and it is sometimes useful to read about a period from the perspective of the time in which it took place. The following comes from "Spaldings Baseball Guide and Official League Book for 1889," written in that same year; the language has not been edited to reflect modern expressions or word usage.')
    sleep(3)
    pyautogui.typewrite('The Joint Rules Committee and their work')
    sleep(3)
    pyautogui.typewrite('The work accomplished by the Joint Rules Committee of the National League and the American Association at their meeting in New York in November, 1888, ranks with the best on record in the revision of the playing rules of the game, and the successful results achieved in improving the code were largely due to the marked efficiency evinced by the chairman of the Committee, Mr. Chas. H. Byrne, the president of the Brooklyn Club, who was indefatigable in doing the large amount of revisory work which was thrown upon the committee. In the face of a very noisy and sensational demand for radical changes in the rules governing the game, the committee, as a whole, manifested a wise conservatism in several respects, which cannot help but be of material assistance')
    sleep(3)
    pyautogui.typewrite(' in advancing the welfare of the game at large. In the first place, by reducing the powers of the attack nearer to an equality with those of the defense -- which result was accomplished when they reduced the number of called balls from five to four -- they not only adopted a rule which will moderate the dangerous speed in delivering the ball to the bat, but they thereby afforded the batsman an additional chance')
    sleep(3)
    pyautogui.typewrite(' for more effective work at the bat. This latter point, too, has been aided by reducing the number of outs the batsman has hitherto been unfairly subjected to. The rule which puts batsmen out on catches of foul balls, which, since the game originated, has been an unfair rule of play, has seen its best day; and this year the entering wedge to its ultimate disappearance has been driven in, with the practical result of the repeal of the foul tip catch. This improvement, too, is in the line of aiding the batting side, as it gets rid of one of the numerous ways of putting the batsman out.')
    sleep(3)
    pyautogui.typewrite('The argument brought to bear in favor of the elimination of outs from foul balls from the code was in the main as follows:')
    sleep(3)
    pyautogui.typewrite('When the batsman hits a fair ball, while at the same time that he gives the fielders a chance to put him out, he himself is also given an equal chance of making a base or of scoring a run; but when he hits a foul ball, while he affords the fielders an opportunity to catch him out, no such compensating advantage is given him in the way of earning a base or a run as in the case of a fair hit ball; and it is in this that the working of the foul ball rule becomes so palpably unjust.')
    sleep(3)
    pyautogui.typewrite(' It is sufficient punishment for hitting a foul ball that he, as batsman, be deprived of making a base, without adding the unjust penalty of an out. This one sided condition of things, too, is increased when a double play is made on the catch of a foul ball, for not only is the batsman unfairly punished, but also the base runner who may have made the base by a clean hit.')
    sleep(3)
    pyautogui.typewrite('It is this latter unfair rule which the committee repealed in getting rid of the foul fly tip; and now a batsman who has earned his base by a safe hit and who runs to the next base on a foul fly tip ball caught by the catcher, can no longer be put out on the double play, as he is now allowed to return to the base he left on the hit, as in the case of a foul ball not caught.')
    sleep(3)
    pyautogui.typewrite('Another step in advance was made by the committee when they officially recognized a sacrifice hit as a factor in team work at the bat. Hitherto far too great a stress has been laid upon the alleged skill of the batsman in making extra hits -- two and three baggers and home runs -- at the cost of giving due credit to the batting which forwards base runners and sends in runs. The work of the slugging batsman who, nearly every time he goes to the bat when no one is on the bases, makes an extra hit, does not compare with that of the team worker who either by a single base hit or a sacrifice hit forwards a runner round the bases, or sends a run in. Here is where the batting averages prove to be complete failures so far as affording a criterion')
    sleep(3)
    pyautogui.typewrite(' of a batsmans value in team work is concerned; which work, by the way, is neither more nor less than that of forwarding base runners or sending runs in by batting -- for one batsman may make four extra base hits in a game without forwarding a runner or sending in a run in a single instance, while another batsman may make but one safe hit and three sacrifice hits, and yet either forward as many runners or send in as many runs.')
    sleep(3)
    pyautogui.typewrite('Probably the best piece of work done by the committee was the amendment they made to the rules governing the umpire, wherein, in defining the powers of an umpire to impose a fine of not less than $5 nor more than $25 for abusive, threatening, or improper language to the umpire, an amendment was made as follows:')
    sleep(3)
    pyautogui.typewrite('"A repetition of the offence shall subject such player to a removal from the game, and the immediate substitution of another player then in uniform."')
    sleep(3)
    pyautogui.typewrite('Lastly, the rule admitting of an extra substitute being allowed to play in the game, at the option of the captain of either of the contesting teams, though an experiment, gives promise of being a desirable amendment. The classifying of the code of rules so as to facilitate the finding of any special rule during the hurry of a contest in progress, was also a desirable improvement. Take it altogether, the present committee did excellent work at their Fall meeting of 1888.')
    sleep(3)
    pyautogui.typewrite('Overrunning the bases')
    sleep(0.01)
    pyautogui.typewrite('Twenty odd years ago George Wright suggested to the Chairman of the old National Associations Committee of Rules that it would be a good plan to allow base runners to overrun first base, giving them the privilege to return and touch the base again without being put out, before attempting to make another base. The suggestion was adopted, and the rule went into effect in 1870, and it has been in operation ever since. When the amendment was presented at the convention of 1869, a delegate wanted the rule applied to all bases, but the majority preferred to test the experiment as proposed at first base. The rule of extending the over-running to all the bases was advocated at the last meeting in 1888 of the Joint')
    sleep(3)
    pyautogui.typewrite(' Committee of Rules, but it was not adopted. The rule is worthy of consideration, in view of the constant sprains and injuries of one kind and another arising from sliding to bases. There has not been a single instance of an injury occurring from the working of the rule of overrunning first base since the rule was adopted, while serious injuries are of daily occurrence in match games,')
    sleep(3)
    pyautogui.typewrite(' arising from collisions at other bases than first, and these are due entirely to the absence of the overrunning rule. The most irritating disputes caused by questions involved in sliding to bases and in running up against base players, are also due to the same cause. Why not put a stop to these injuries and these disputes by giving the base runner the same privileges in overrunning second, third, and home bases that he now has in overrunning first base? In every way will the adoption of the rule suggested be an improvement, and not the least of its advantages will be its gain to base running, which is, next to fielding, the most attractive feature of our game.')
    sleep(3)
    pyautogui.typewrite('The patrons of ball grounds')
    sleep(3)
    pyautogui.typewrite('There are two classes of the patrons of professional baseball grounds which club Presidents and Directors have their choice in catering to for each season, and these are, first, the reputable class, who prefer to see the game played scientifically and by gentlemanly exemplars of the beauties of the game; and second, the hoodlum element, who revel in noisy coaching, "dirty ball playing," kicking against the umpires, and exciting disputes and rows in every inning. The Chicago, Philadelphia, and Boston Clubs in the League have laid out nearly $200,000 within the past two years in constructing their grounds for the express purpose of eliciting the very best patronage of their respective cities. The Brooklyn Club have excelled in this')
    sleep(3)
    pyautogui.typewrite(' respect in the American Association by constructing their grounds for a similar class of patrons. But all of the clubs have not followed this example, the majority committing the blunder of considering only the tastes and requirements of the hoodlum class apparently in catering for patronage. This is a great financial mistake. Experience has shown conclusively that it pays best to cater solely for the best class of patronage.')
    sleep(3)
    pyautogui.typewrite(' The work in doing this is so much more satisfactory for one thing, and it is sure to be the most remunerative. If there is any sport which yields a fair equivalent in the special attractions it presents for an admission fee of half a dollar, it is such ball playing as was exhibited during the past season on the grounds of the leading clubs of the National League. A feature of the attendance at the League games of 1888 was the presence of the')
    sleep(3)
    pyautogui.typewrite(' fair sex in such goodly numbers. Where the ladies congregate as spectators of sports a refining influence is brought to bear which is valuable to the welfare of the game. Besides which, the patronage of ladies improves the character of the assemblages and helps to preserve the order without which first-class patronage cannot be obtained.')
    sleep(5)

def baseball():
    if (pyautogui.locateOnScreen('images/baseball.png') is not None):
        baseballFile()

aesop()
tiger()
zebra()
oz()
enchanted()
astronauts()
